notifications: # set notification options
  email:
    recipients:
      - one@example.com


    # change is when the repo status goes from pass to fail or vice versa
    on_success: [always|never|change]
    on_failure: [always|never|change]
  # Or we could just disable all email
  email: false

before_deploy:
- gem install mime-types -v 2.6.2