language: ruby
rvm:
- 2.3.0
before_script:
- bundle exec rake db:setup
- bundle exec rake db:migrate
- RAILS_ENV=test bundle exec rake db:setup
- RAILS_ENV=test bundle exec rake db:migrate
script:
- bundle exec cucumber
- bundle exec rspec
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: LTNl3uwSaXIIQYRY2XZn+tKhHA72W8BHnjM22giLC6ILfHHVl8Zg2seOx7ofh6e5XCgLgNbPRSfq/iw+KIxQIbPv5EWZZ18MJwRb0IRYHpGutmywqFPY4fDmhPTFo0XwOAL1uYp2OGyLC0ypgzyQmkRJxz4+T503ZpLeQglxIHO0SV6XJhsTkaQg44Spx1RoDupYHM4u68zIMEt5nv4A4OrKwjKXcIcjOr2cyTXH3tA+6cg0eoGKy6Tjawq1BDfCsK1VHt3DiJHZtgAcmvAfpFHVFyuT+ots9YEtGqm0n/bnawdVBWRmM/8m1E+U4+3BvFKma7TPpH7sbuIbpHElPVpLcFjmfy0l/+IRrR+XcTUUU+zb8IDBNMvSo2lEDKXUqFCMIC1rf1lHgK6esjjta2QtOf1uWPrr248LSWenChwVqC5DaAP/HR/5Y8tdPtijVm21m1CghhlU/W0fFpAzsFEpm/5CCWXg605jsOYtzM2GdtxB+qkH8KEjHX2MyAvm20z3CrpZ6/BPdV+vGoTgsRPww9VL0WYp3un6lI4jLZLigky7MpREd2hpEIGy+BlMFG0zuafT2vUN9A7LA3DUnSECak257NRXudw2+Now9F5nxGYdvhXTamjaCD5Dt2QRLIX6uMPI6P/ZOZncn/blECnOfeewA9Vz7p9FRYBU3a4=
  app: Serler_CoDoctors
  on:
    repo: tdbt1985/Serler_Stream2
    branch: CoDoctors
