postgresql: &postgresql
  adapter: postgresql
  username: postgres
  password:
#  database: strano_<%= Rails.env %>
#  min_messages: ERROR

defaults: &defaults
  pool: 5
  timeout: 5000
#  port: 5432
  host: localhost
  <<: *<%= ENV['DB'] || "postgresql" %>

development:
  <<: *defaults
  database: SERLER_Stream2_dev

test:
  <<: *defaults
  database: SERLER_Stream2_test

production:
  <<: *defaults
  database: SERLER_Stream2_pro

cucumber:
  <<: *test
